# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration Test

on:
  push:
    branches: [main, release, development]
  pull_request:
    branches: [main, release, development]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Devnet
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v3
      - run: sudo chmod -R 7777 /home/runner/work/metamui-sdk/metamui-sdk
      - run: sudo yarn
      - run: yarn test:dev
